// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MudBlazor6.Models;

public partial class Job
{
    public int JobId { get; set; } = 0;

    public string JobName { get; set; }=string.Empty;

    public int WorkshopId { get; set; }

    public int UnitId { get; set; }

    public virtual Unit Unit { get; set; }

    public virtual Workshop Workshop { get; set; }
}