// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace MudBlazor6.Models;

public partial class User
{
    public int UserId { get; set; } = 0;

    public string UserName { get; set; }=string.Empty;

    public string Role { get; set; }

    public string Password { get; set; }
    /*
     Создание ClaimPrincipal с именем пользователя, паролем и ролью.
     Claim - утверждение - атрибут субъекта проверки подлинности, в данном методе - имя пользователя, пароль, роль в приложении. ClimeTypes - возможные типы утверждений
     ClaimIdentity - коллекция утрверждений, реализация удостоверения описываемого коллекцией утверждений
     ClaimPrincipal - коллекция утверждений, обычно содержит один элемент ClaimsIdentity
     В данном методе сначала создается коллекция ClaimsIdentity из трех объектов Claim (имя, пароль и роль). "ControlJob" - параметр определяющий тип проверки
     подлинности или схемы проверки подлинности. В данном примере это своя схема, но может быть и например проверка через куки "Cookies" и др.
     Далее создается ClaimPrincipal с входящим созданным ClaimsIdentity.
     */
    public ClaimsPrincipal ToClaimsPrincipal() => new(new ClaimsIdentity(new Claim[]
      { new Claim(ClaimTypes.Name,UserName),
        new Claim(ClaimTypes.Hash,Password),
        new Claim(ClaimTypes.Role,Role)},
        "ControlJob"));

    /*
     * Извлечение имени пользователя, пароля и роли и объекта ClaimPrincipal
     */
    public static User FromClaimsPrincipal(ClaimsPrincipal principal) => new()
    {
        UserName = principal.FindFirst(ClaimTypes.Name)?.Value ?? string.Empty,
        Password = principal.FindFirst(ClaimTypes.Hash)?.Value ?? string.Empty,
        Role = principal.FindFirst(ClaimTypes.Role)?.Value ?? string.Empty
    };
}