// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MudBlazor6.Models;

public partial class Workshop
{
    public int WorkshopId { get; set; } = 0;

    public string WorkshopName { get; set; }=string.Empty;

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}